-- Orgullo Embajador — combined security remediation migrations
--
-- Generated by concatenating, verbatim, the three real migration files
-- already committed in this project:
--   supabase/migrations/0018_profiles_role_escalation_fix.sql
--   supabase/migrations/0019_wompi_orders_access_token.sql
--   supabase/migrations/0020_rate_limit_events.sql
-- Nothing below was rewritten or reconstructed — each section is an exact
-- copy of its source file. Run once in Supabase SQL Editor, top to bottom.
-- Safe to re-run: every statement uses IF NOT EXISTS / OR REPLACE / DROP..IF EXISTS.

-- =========================================================================
-- 0018
-- =========================================================================

-- Orgullo Embajador — close the self-promotion hole in profiles RLS
--
-- Security audit finding (CRÍTICO): "profiles_update_own" (0001_admin_panel.sql,
-- reaffirmed identically in 0003_sync_profiles.sql) is `for update using
-- (auth.uid() = id)` with NO `with check`. Postgres reuses `using` as the
-- check for the post-update row when `with check` is omitted — and
-- `auth.uid() = id` stays true no matter what else changes in the same
-- UPDATE, including `role`. Any authenticated user can currently call the
-- Supabase REST API directly (their own publishable key + their own JWT,
-- bypassing this app entirely) and set their own role to 'admin'. Since
-- verifyAdmin() and is_admin() both trust profiles.role read live from the
-- DB, this is a full admin-panel + financial-data takeover from a plain
-- signup, with zero code path in this app involved.
--
-- Fix: `current_profile_role()` (security definer, bypasses RLS so it can't
-- recurse/be blocked by the very policy it supports) reads the role
-- currently stored for the caller. The new `with check` requires the
-- post-update row's `role` to equal that — i.e. an UPDATE that doesn't
-- touch `role` always passes (full_name/email edits keep working exactly
-- as before), but any UPDATE that tries to *change* `role` is rejected by
-- Postgres before it's ever written. This does not depend on the app
-- hiding a button or checking anything client-side.
--
-- Legitimate role changes still go through POST /api/admin/users/update-role,
-- which uses getSupabaseAdmin() (the service-role client bypasses RLS
-- entirely) — that flow is untouched and keeps working exactly as before.
--
-- Run this once in the Supabase dashboard: SQL Editor > New query > paste > Run.

create or replace function public.current_profile_role()
returns text
language sql
security definer set search_path = public
stable
as $$
  select role from public.profiles where id = auth.uid();
$$;

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id and role = public.current_profile_role());

notify pgrst, 'reload schema';

-- (The read-only audit query that normally follows here in 0018 is
-- intentionally moved to the very end of this combined file — see below —
-- so it runs last, after all three migrations, as requested.)

-- =========================================================================
-- 0019
-- =========================================================================

-- Orgullo Embajador — per-order access token for Wompi's public status routes
--
-- Security audit finding (MEDIO): /api/wompi/order-status and
-- /api/wompi/mark-redirected were reachable with only `reference`, which
-- has just ~32 bits of real randomness (a Date.now() prefix + 8 hex chars)
-- and is sent to Wompi's own checkout form — not a strong enough secret to
-- gate the buyer's own name/WhatsApp/email (embedded in the returned
-- whatsappUrl once an order is paid).
--
-- access_token is a separate, high-entropy (122-bit) secret that is never
-- sent to Wompi at all — it only ever travels inside our own redirect-url,
-- round-tripping through the buyer's own browser. Both routes now require
-- it to match before returning anything or accepting a write.
--
-- Nullable initially so this migration never fails on existing rows (there
-- should be none of consequence yet — Wompi went live very recently — but
-- this is non-destructive either way: old orders without a token simply
-- can no longer be polled/marked, which only matters for a payment that
-- was mid-flight at the exact moment this runs).
-- Run this once in the Supabase dashboard: SQL Editor > New query > paste > Run.

alter table public.wompi_orders add column if not exists access_token text;

create unique index if not exists wompi_orders_access_token_idx
  on public.wompi_orders (access_token)
  where access_token is not null;

notify pgrst, 'reload schema';

-- =========================================================================
-- 0020
-- =========================================================================

-- Orgullo Embajador — shared, persistent rate-limit store
--
-- Security audit finding (MEDIO): /api/checkout, /api/wompi/create-order,
-- /api/auth/register, /api/visit have no throttling — deliberately not an
-- in-memory counter (Vercel's serverless functions run as multiple,
-- short-lived instances with no shared memory, so an in-process counter
-- would silently under-count and give no real protection). This table is
-- the same durable-counter pattern already proven by admin_access_logs'
-- rate limiting (src/app/api/admin/access-log/route.ts) — a shared,
-- server-side, Supabase-backed store every instance reads/writes the same
-- way.
--
-- `key` encodes route + identifier (e.g. "checkout:203.0.113.5") so one
-- table serves every throttled endpoint. Rows are small and short-lived by
-- purpose (a rate-limit window is a few minutes), but nothing here
-- auto-deletes old rows yet — acceptable for now given the tiny row size;
-- worth a periodic cleanup later if volume grows.
--
-- Run this once in the Supabase dashboard: SQL Editor > New query > paste > Run.

create table if not exists public.rate_limit_events (
  id uuid primary key default gen_random_uuid(),
  key text not null,
  created_at timestamptz not null default now()
);

create index if not exists rate_limit_events_key_created_at_idx
  on public.rate_limit_events (key, created_at);

-- RLS enabled with NO policies — same reasoning as sales/sale_items/
-- admin_access_logs: only the service-role client (server routes) ever
-- touches this table.
alter table public.rate_limit_events enable row level security;

notify pgrst, 'reload schema';

-- =========================================================================
-- AUDIT QUERY (from 0018) — read-only, run last.
-- Lists everyone currently marked as admin, so you can confirm the list
-- matches who you actually expect.
-- =========================================================================
select id, email, role from public.profiles where role = 'admin' order by email;
